version: '3.8'

services:
  eventstore:
    image: eventstore/eventstore:latest
    restart: unless-stopped
    ports:
      - "2113:2113"
      - "1113:1113"
    command: >
      --insecure
      --run-projections=All
      --enable-external-tcp
      --enable-atom-pub-over-http
